# Bayesian inference & machine learning example: handwritten postcode recognition

France's La Poste has used automated sorting since 1964.

A sample of postcodes:
- 2000
- 3122
- 4350
- A-1220 (Vienna, Austria)
- Tsuen Wan (Hong Kong): no postcodes in HK
- 02138 (Cambridge, MA)
- EC1V 4AD (London)
- 8007 (PO boxes in Collins Street West)
- 2570 (belongs to 22 towns and suburbs around Camden, NSW, according to Wikipedia)

What prior information?

- Do all Australian postcodes have 4 digits? Yes.
- What range? 0200 to 9944
- What proportion of mail our system sees is for Australia versus overseas? 80% (assumed)
- 25% (assumed) of all mail goes to these 10 postcodes: 2000, 2001, 3000, 3001, 4000, 4001, 5000, 5001, 6000, 6001.
- What population for each postcode? (and how to handle this when e.g. Paramatta NSW has 2150 for street addresses and 2124 for postcodes). If we don't have population info by postcode, how about using a prior with state population data?
   - NSW: postcodes 1000-1999 (PO boxes), 2000-2599, 2620-2899, 2921-2999
   - ACT: 0200-0299 (PO boxes), 2600-2619, 2900-2920
   - VIC: 3000-3999, 8000-8999 (PO boxes)
   - QLD: 4000-4999, 9000-9999 (PO boxes)
   - SA: 5000-5799, 5800-5999 (PO boxes)
   - WA 6000-6797, 6800-6999 (PO boxes)
   - TAS: 7000-7799, 7800-7999 (PO boxes)
   - NT: 0800-0899, 0900-0999 (PO boxes)

### How do we encode this prior information for machine learning purposes?

In [1]:
postcodes_by_state = dict((
    ('Australian Capital Territory', set(range(2600, 2620)) | set(range(2900, 2920))),
    ('New South Wales', set(range(2000, 3000)) - set(range(2600, 2620)) - set(range(2900, 2920))),
    ('Victoria', set(range(3000, 4000))),
    ('Queensland', set(range(4000, 5000))),
    ('South Australia', set(range(5000, 5800))),
    ('Western Australia', set(range(6000, 6798))),
    ('Tasmania', set(range(7000, 7800))),
    ('Northern Territory', set(range(800, 900)))
))

### Goal: construct a prior $p(\textrm{postcode})$ over all 4-digit postcodes, where 0 represents invalid / missing / international.

We will start by using state populations as a proxy for really knowing the proportion of mail sent to each postcode. (If we obtain more data, we can update and improve our model by applying Bayes' theorem later.)

#### State populations

In [2]:
import pandas as pd

In [3]:
def fetch_state_populations():
    url = 'http://www.ausstats.abs.gov.au/Ausstats/subscriber.nsf/0/D52DEAAFCEDF7B2ACA2580EB00133359/$File/31010do001_201609.xls'

    state_populations = pd.read_excel(url, sheetname='Table_8', skiprows=6,
                  names=['State', 'Population', '%'])

    state_populations.set_index('State', inplace=True)

    drop_row_idx = list(state_populations.index).index('Other Territories')

    state_populations.drop(state_populations.index[drop_row_idx:], inplace=True)

    state_populations['Population'] = state_populations['Population'].astype(int)
    # state_populations.to_hdf('state_populations.h5', key='populations')
    return state_populations

In [4]:
state_populations = pd.read_hdf('state_populations.h5')

In [5]:
state_populations

Population     %
State                                         
New South Wales                  7757843  32.0
Victoria                         6100877  25.2
Queensland                       4860448  20.1
South Australia                  1710804   7.1
Western Australia                2623164  10.8
Tasmania                          519783   2.1
Northern Territory                245657   1.0
Australian Capital Territory      398349   1.6

These are the desired feature expectations for each state.

In [6]:
state_populations['%'].sum()

99.900000000000006

(This excludes the other territories, like Norfolk Island. Ignore this for now.)

### How to incorporate this?

... to model the probability of e.g. $p(\textrm{postcode}=3122)$?

In [7]:
def prior_state(state):
    return state_populations['%'].loc[state] / 100

In [8]:
prior_state('New South Wales')

0.32000000000000001

Now we have a prior p(state).

### Bayes theorem:

$p(\textrm{postcode}) = \sum_{\textrm{all states}} p(\textrm{postcode | state}) p(\textrm{state})$

### Exercise:

Assuming you have a function `prior_postcode_given_state(postcode, state)`, implement this as a function `prior_postcode(postcode)`.

In [9]:
all_states = list(state_populations.index)
all_states

['New South Wales',
 'Victoria',
 'Queensland',
 'South Australia',
 'Western Australia',
 'Tasmania',
 'Northern Territory',
 'Australian Capital Territory']

In [10]:
prior_state('Australian Capital Territory')

0.016

In [11]:
def prior_postcode(postcode):
    p = 0.0
    for state in all_states:
        p += prior_postcode_given_state(postcode, state) * prior_state(state)
    assert p <= 1
    return p

### Exercise:

- Write a function `prior_postcode_given_state(postcode, state)` that assigns equal probability to each valid postcode in the corresponding state (or 0 probability for the wrong state).

In [12]:
def prior_postcode_given_state(postcode, state):
    postcodes = postcodes_by_state[state]
    return 1 / len(postcodes) if postcode in postcodes else 0

In [13]:
prior_postcode_given_state(3122, 'Victoria')

0.001

In [14]:
prior_postcode(3122)

0.000252

## Maximum entropy models: the easy way

Above we informally constructed a prior model that was as *flat* (uninformative) as possible subject to the constraint that the proportion of mail being delivered to a postcode is equal to the state's population, divided by the number of postcodes for that state.

Now we show how to derive such prior models in a more principled way using the `scikit-maxentropy` module.

In [217]:
import numpy as np
samplespace = np.arange(10000, dtype=np.uint16)

Define 0000 as "other": i.e. all international postcodes, all those addresses missing a postcode, etc.

In [16]:
samplespace

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=uint16)

In [17]:
from maxentropy.skmaxent import MaxEntTransformer, MaxEntPrior

In [222]:
def is_valid(postcodes):
    return [200 <= postcode < 10000 for postcode in postcodes]

In [223]:
def is_nsw_street(postcodes):
    return [postcode in postcodes_by_state['New South Wales'] for postcode in postcodes]

In [224]:
def is_act_street(postcodes):
    return [postcode in postcodes_by_state['Australian Capital Territory'] for postcode in postcodes]

In [225]:
def is_vic_street(postcodes):
    return [postcode in postcodes_by_state['Victoria'] for postcode in postcodes]

In [226]:
def is_qld_street(postcodes):
    return [postcode in postcodes_by_state['Queensland'] for postcode in postcodes]

In [227]:
def is_sa_street(postcodes):
    return [postcode in postcodes_by_state['South Australia'] for postcode in postcodes]

In [228]:
def is_wa_street(postcodes):
    return [postcode in postcodes_by_state['Western Australia'] for postcode in postcodes]

In [229]:
def is_tas_street(postcodes):
    return [postcode in postcodes_by_state['Tasmania'] for postcode in postcodes]

In [230]:
def is_nt_street(postcodes):
    return [postcode in postcodes_by_state['Northern Territory'] for postcode in postcodes]

In [231]:
features = [is_valid,
            is_nsw_street, is_act_street, is_vic_street, is_qld_street,
            is_sa_street, is_wa_street, is_tas_street, is_nt_street]

In [232]:
transformer = MaxEntTransformer(features, samplespace, format='ndarray', verbose=False)

In [234]:
X = np.array([[2000, 3122, 90210, 8007, 5001]]).T
X

array([[ 2000],
       [ 3122],
       [90210],
       [ 8007],
       [ 5001]])

In [235]:
transformer.transform(X).A

array([[ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.]])

In [97]:
samplespace

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=uint16)

In [98]:
samplespace.reshape(-1, 1)

array([[   0],
       [   1],
       [   2],
       ..., 
       [9997],
       [9998],
       [9999]], dtype=uint16)

In [99]:
from maxentropy.maxentutils import evaluate_feature_matrix

In [100]:
F = evaluate_feature_matrix(features, samplespace, format='ndarray')

In [101]:
F.shape

(8, 10000)

In [102]:
%timeit evaluate_feature_matrix(features, samplespace, format='ndarray')

10 loops, best of 3: 21.5 ms per loop


#### Performance oddity with range() and numpy integers

In [103]:
%timeit samplespace[1000] in range(1000)   # super slow!! with a 16-bit uint dtype

1000 loops, best of 3: 1.43 ms per loop


In [104]:
s = set(range(1000))

In [105]:
%timeit samplespace[1000] in s             # much faster

The slowest run took 56.17 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 136 ns per loop


In [106]:
thing = np.array(1000, dtype=int)

In [107]:
%timeit thing in range(1000)               # also very slow

1000 loops, best of 3: 819 µs per loop


In [108]:
%timeit 1000 in range(1000)                # even this is slower than a set. Poor implementation of range.__contains__!

The slowest run took 8.26 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 365 ns per loop


### Back to the model

In [109]:
samplespace.reshape(-1, 1)

array([[   0],
       [   1],
       [   2],
       ..., 
       [9997],
       [9998],
       [9999]], dtype=uint16)

In [110]:
F = transformer.transform(samplespace.reshape(-1, 1))

In [111]:
# %timeit F = transformer.transform(samplespace.reshape(-1, 1))

In [112]:
F

<10000x8 sparse matrix of type '<class 'numpy.float64'>'
	with 5498 stored elements in Compressed Sparse Row format>

In [113]:
k = F.mean(axis=0)

In [114]:
k

matrix([[ 0.096 ,  0.004 ,  0.1   ,  0.1   ,  0.08  ,  0.0798,  0.08  ,
          0.01  ]])

These are the empirical expectations over the entire sample space, weighting all postcodes from 0 to 9999 equally.

More likely, we would want to supply the desired feature expectations as constraints from **prior knowledge** and/or compute the expectations on an actual dataset.

Here is an example: suppose we know that:
- 

In [210]:
k = np.array([[#0.95,
               0.3, 0.05, 0.25, 0.2, 0.1, 0.05, 0.025, 0.025]])

In [211]:
k.shape

(1, 8)

In [212]:
model = MaxEntPrior(features, samplespace, format='ndarray', verbose=False)

In [213]:
model

MaxEntPrior(features=[<function is_nsw_street at 0x111aaaae8>, <function is_act_street at 0x111aaa7b8>, <function is_vic_street at 0x111aaa488>, <function is_qld_street at 0x111aaa510>, <function is_sa_street at 0x111aaa840>, <function is_wa_street at 0x111aaaa60>, <function is_tas_street at 0x111aaa158>, <function is_nt_street at 0x111aea1e0>],
      format='ndarray',
      samplespace=array([   0,    1, ..., 9998, 9999], dtype=uint16),
      vectorized=True, verbose=False)

In [214]:
model.fit(k)

MaxEntPrior(features=[<function is_nsw_street at 0x111aaaae8>, <function is_act_street at 0x111aaa7b8>, <function is_vic_street at 0x111aaa488>, <function is_qld_street at 0x111aaa510>, <function is_sa_street at 0x111aaa840>, <function is_wa_street at 0x111aaaa60>, <function is_tas_street at 0x111aaa158>, <function is_nt_street at 0x111aea1e0>],
      format='ndarray',
      samplespace=array([   0,    1, ..., 9998, 9999], dtype=uint16),
      vectorized=True, verbose=False)

In [216]:
model.params_

array([ 15.75136371,  17.1376572 ,  15.52822002,  15.30507631,
        14.83507262,  14.14442807,  13.44877592,  15.52821932])

In [178]:
len(features)

8

In [179]:
samplespace.shape

(10000,)

In [180]:
k.shape

(1, 8)

In [181]:
model.model.F.shape

(8, 10000)

In [182]:
model.model.resetparams()

In [183]:
model.model.params

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [184]:
from maxentropy import model

In [185]:
maxentmodel = model.Model(features, samplespace, format='ndarray')

In [186]:
k.shape

(1, 8)

In [187]:
maxentmodel.F

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [188]:
maxentmodel.F.mean()

0.068724999999999994

In [189]:
maxentmodel.F.shape

(8, 10000)

In [190]:
maxentmodel.resetparams()

In [191]:
maxentmodel.params

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [192]:
maxentmodel.lognormconst()

9.2103403719761836

In [193]:
maxentmodel.expectations()

array([ 0.096 ,  0.004 ,  0.1   ,  0.1   ,  0.08  ,  0.0798,  0.08  ,  0.01  ])

In [194]:
k

array([[ 0.3  ,  0.05 ,  0.25 ,  0.2  ,  0.1  ,  0.05 ,  0.025,  0.025]])

In [195]:
maxentmodel.probdist()

array([  1.00000000e-04,   1.00000000e-04,   1.00000000e-04, ...,
         1.00000000e-04,   1.00000000e-04,   1.00000000e-04])

So each postcode on the sample space has a probability $10^{-4}$ under our unfitted prior model.

In [196]:
maxentmodel.showdist()

	x = 0               	p(x) = 0.000
	x = 1               	p(x) = 0.000
	x = 2               	p(x) = 0.000
	x = 3               	p(x) = 0.000
	x = 4               	p(x) = 0.000
	x = 5               	p(x) = 0.000
	x = 6               	p(x) = 0.000
	x = 7               	p(x) = 0.000
	x = 8               	p(x) = 0.000
	x = 9               	p(x) = 0.000
	...
	x = 9990            	p(x) = 0.000
	x = 9991            	p(x) = 0.000
	x = 9992            	p(x) = 0.000
	x = 9993            	p(x) = 0.000
	x = 9994            	p(x) = 0.000
	x = 9995            	p(x) = 0.000
	x = 9996            	p(x) = 0.000
	x = 9997            	p(x) = 0.000
	x = 9998            	p(x) = 0.000
	x = 9999            	p(x) = 0.000


In [199]:
maxentmodel.fit(np.squeeze(k))

In [200]:
maxentmodel.params

array([ 16.36928448,  17.75557723,  16.14614102,  15.9229976 ,
        15.45299359,  14.76234888,  14.06670155,  16.14614269])

In [202]:
maxentmodel.expectations()

array([ 0.29999996,  0.04999991,  0.24999999,  0.20000002,  0.09999997,
        0.04999995,  0.02500005,  0.02500004])

In [206]:
maxentmodel.params

array([ 16.36928448,  17.75557723,  16.14614102,  15.9229976 ,
        15.45299359,  14.76234888,  14.06670155,  16.14614269])

In [205]:
maxentmodel.probdist()

array([  2.43086052e-11,   2.43086052e-11,   2.43086052e-11, ...,
         2.43086052e-11,   2.43086052e-11,   2.43086052e-11])